/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.bwf.view;

import java.io.IOException;
import java.io.ObjectOutputStream;

import javax.swing.JOptionPane;

import com.bwf.client.ClientDemo;
import com.bwf.jar.MyRequest;
import com.bwf.jar.MyResponse;
import com.bwf.util.UiUtil;

/**
 *
 * @author admin
 */
public class PwdFrame extends javax.swing.JFrame {

	private ObjectOutputStream oos;
	MyResponse lastResponse;
	//
	private String uName;

	/**
	 * Creates new form PwdFrame
	 */
	public PwdFrame(ObjectOutputStream oos, MyResponse lastResponse, String uName) {
		// 初始化在复制之后
		this.oos = oos;
		this.lastResponse = lastResponse;
		this.uName = uName;
		initComponents();
		init();
	}

	private void init() {
		this.setTitle("不氪金你怎么变强");
		// 不可调大小
		this.setResizable(false);
		UiUtil.setFrameCenter(this);
		UiUtil.setFrameImage(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jOldPwdField = new javax.swing.JTextField();
		jNewPwdField = new javax.swing.JTextField();
		jSurePwdField = new javax.swing.JTextField();
		jOkButton = new javax.swing.JButton();
		jCancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
		jLabel1.setText("修改密码");

		jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel2.setText("旧密码：");

		jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel3.setText("新密码：");

		jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel4.setText("确认密码：");

		jOldPwdField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jOldPwdFieldActionPerformed(evt);
			}
		});

		jNewPwdField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jNewPwdFieldActionPerformed(evt);
			}
		});

		jSurePwdField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jSurePwdFieldActionPerformed(evt);
			}
		});

		jOkButton.setText("确认");
		jOkButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jOkButtonActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jCancelButton.setText("取消");
		jCancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(53, 53, 53)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3).addComponent(jLabel2).addComponent(jLabel4))
										.addGap(28, 28, 28)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(jOldPwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jNewPwdField, javax.swing.GroupLayout.PREFERRED_SIZE, 157,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jSurePwdField, javax.swing.GroupLayout.PREFERRED_SIZE,
														157, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
										.addComponent(jOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84,
												Short.MAX_VALUE)
										.addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(81, 81, 81)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel1).addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(jOldPwdField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(36, 36, 36)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jNewPwdField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
				.addGap(32, 32, 32)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(jSurePwdField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(38, 38, 38)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jOldPwdFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jNewPwdFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jSurePwdFieldActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jOkButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
		// 确认按钮
		// 第一步，先让用户输入旧密码进行验证,然后输入修改后的密码
		String oldPwd = this.jOldPwdField.getText().trim();
		String newPwd = this.jNewPwdField.getText().trim();
		String secondNewPwd = this.jSurePwdField.getText().trim();

		// 判断
		if (!newPwd.equals(secondNewPwd)) {
			JOptionPane.showMessageDialog(this, "两次输入密码不一致,请重新输入");
			// 重置按钮 -- 置空
			reset();
			return;
		} else {
			MyRequest request = new MyRequest(MyRequest.TYPE_CHANGEPWD);
			request.getUmap().put(MyRequest.MEG_USERNAME, uName);
			request.getUmap().put(MyRequest.MEG_USERPWD, oldPwd);
			request.getUmap().put(MyRequest.MEG_LEVEL, "彩民");
			request.getUmap().put(MyRequest.MEG_NEWPWD, newPwd);
			// 包装好了，就发送过去，序列化
			oos.writeObject(request);
			oos.flush();

			synchronized (ClientDemo.class) {
				if (ClientDemo.lastResponse == null) {
					try {
						ClientDemo.class.wait();
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}

				// 读到了消息
				MyResponse lastResponse = ClientDemo.lastResponse;
				ClientDemo.lastResponse = null;
				System.out.println(lastResponse.getrMeg().get(MyResponse.MEG_CONTENT));
				// 判断是否修改成功
				if (lastResponse.isSuccess()) {
					// 修改成功！！
					JOptionPane.showMessageDialog(this, "修改成功");
					goBuyerFrame();
				} else {
					// 修改失败，密码不正确
					JOptionPane.showMessageDialog(this, "旧密码输入错误");
					reset();
				}

				ClientDemo.class.notify();
			}
		}

	}

	private void reset() {
		// 重置置空
		this.jOldPwdField.setText("");
		this.jNewPwdField.setText("");
		this.jSurePwdField.setText("");
		this.jOldPwdField.requestFocus();
	}

	private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// 取消按钮
		goBuyerFrame();
		
	}

	private void goBuyerFrame() {
		// 返回彩民主页
		BuyerFrame bf = new BuyerFrame(oos,lastResponse,uName);
		bf.setVisible(true);
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(PwdFrame.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(PwdFrame.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(PwdFrame.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(PwdFrame.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new PwdFrame().setVisible(true);
	// }
	// });
	// }

	// Variables declaration - do not modify
	private javax.swing.JButton jCancelButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jNewPwdField;
	private javax.swing.JButton jOkButton;
	private javax.swing.JTextField jOldPwdField;
	private javax.swing.JTextField jSurePwdField;
	// End of variables declaration
}
